### ISSUE TITLE
Usage Clarification

### ISSUE THREAD

**Issue by TortoiseHam** [cvjena/cifair#1]
Hey, thanks so much for taking the time to identify this problem. It's amazing that those datasets went so long without vetting. I'd like to incorporate your data loader code into an ML framework so people can access the datasets more easily, but I was wondering if you could confirm that the loader code is in the public domain. Thanks!

**Comment by Callidior** [comment]
Hey,
I am happy to confirm that you can freely use the loader code and just added a CC0 license file to that directory.
Thanks for asking and for increasing the reach of this version of the dataset!

**Comment by TortoiseHam** [comment]
Fantastic, thanks :)
